export const ADD_NEW_REQUEST = 'ADD_NEW_REQUEST';
export const REQUEST_REQUESTED = 'REQUEST_REQUESTED';
export const REQUEST_RECEIVED = 'REQUEST_RECEIVED';
export const ADD_ITEM = 'ADD_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
