require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RequestItemsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # RequestItem. As you add validations to RequestItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RequestItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all request_items as @request_items" do
      request_item = RequestItem.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:request_items)).to eq([request_item])
    end
  end

  describe "GET show" do
    it "assigns the requested request_item as @request_item" do
      request_item = RequestItem.create! valid_attributes
      get :show, {:id => request_item.to_param}, valid_session
      expect(assigns(:request_item)).to eq(request_item)
    end
  end

  describe "GET new" do
    it "assigns a new request_item as @request_item" do
      get :new, {}, valid_session
      expect(assigns(:request_item)).to be_a_new(RequestItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested request_item as @request_item" do
      request_item = RequestItem.create! valid_attributes
      get :edit, {:id => request_item.to_param}, valid_session
      expect(assigns(:request_item)).to eq(request_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RequestItem" do
        expect {
          post :create, {:request_item => valid_attributes}, valid_session
        }.to change(RequestItem, :count).by(1)
      end

      it "assigns a newly created request_item as @request_item" do
        post :create, {:request_item => valid_attributes}, valid_session
        expect(assigns(:request_item)).to be_a(RequestItem)
        expect(assigns(:request_item)).to be_persisted
      end

      it "redirects to the created request_item" do
        post :create, {:request_item => valid_attributes}, valid_session
        expect(response).to redirect_to(RequestItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved request_item as @request_item" do
        post :create, {:request_item => invalid_attributes}, valid_session
        expect(assigns(:request_item)).to be_a_new(RequestItem)
      end

      it "re-renders the 'new' template" do
        post :create, {:request_item => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested request_item" do
        request_item = RequestItem.create! valid_attributes
        put :update, {:id => request_item.to_param, :request_item => new_attributes}, valid_session
        request_item.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested request_item as @request_item" do
        request_item = RequestItem.create! valid_attributes
        put :update, {:id => request_item.to_param, :request_item => valid_attributes}, valid_session
        expect(assigns(:request_item)).to eq(request_item)
      end

      it "redirects to the request_item" do
        request_item = RequestItem.create! valid_attributes
        put :update, {:id => request_item.to_param, :request_item => valid_attributes}, valid_session
        expect(response).to redirect_to(request_item)
      end
    end

    describe "with invalid params" do
      it "assigns the request_item as @request_item" do
        request_item = RequestItem.create! valid_attributes
        put :update, {:id => request_item.to_param, :request_item => invalid_attributes}, valid_session
        expect(assigns(:request_item)).to eq(request_item)
      end

      it "re-renders the 'edit' template" do
        request_item = RequestItem.create! valid_attributes
        put :update, {:id => request_item.to_param, :request_item => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested request_item" do
      request_item = RequestItem.create! valid_attributes
      expect {
        delete :destroy, {:id => request_item.to_param}, valid_session
      }.to change(RequestItem, :count).by(-1)
    end

    it "redirects to the request_items list" do
      request_item = RequestItem.create! valid_attributes
      delete :destroy, {:id => request_item.to_param}, valid_session
      expect(response).to redirect_to(request_items_url)
    end
  end

end
